### ISSUE TITLE
Screenscrapper "msx2" not working

### ISSUE THREAD

**Issue by qqplayer** [muldjord/skyscraper#1]
I have found a problem scrapping my games using the website "screenscraper"
Worked great with msx but when I try to scrappe msx2 it doesnt found anyone.
I think is because they have separate folders for msx and msx2 games.

> MSX2 - SCREENSCRAPER - Base de données et téléchargement ...

https://www.screenscraper.fr/gamesinfos.php?plateforme=116&alpha=0&numpage=0

Can you please take a look at this?

UPDATE1: Looking at the website link it shows "plateforme=116" for MSX2 and "plateforme=113" for MSX , maybe this can help.

PD: Congrats for your work , I have tested your tool and I think is the best scrapper ever.

**Comment by muldjord** [comment]
Fixed in 2.0.2. Please test it and let me know how it goes. Roms for all msx family machines should be in 'msx' folder.

**Comment by qqplayer** [comment]
I forget to say Im using Skyscrapper on Ubuntu 16.04
So it works great with my msx roms but with msx2 always get the same error.

> This is NOT going well! I guit! *slams the door*
No, seriously, out of 30 files we had 30 misses, which probably means you are using a scraping source that doesn't support this platform. Please be considerate and choose a scraping module that supports the platform you are scraping (check '--help').

I even move my roms to another place:

`Skyscraper -p 'msx' -i '/media/user/hdd1/skyscrapper/msx/' -f 'attractmode' -e 'Microsoft MSX' -s 'screenscraper'
`

My rom names are like on msx , and I can find them on the website:

> 1942 .zip,Aleste.zip

Thanks again for your work.

**Comment by muldjord** [comment]
So did you test it with 2.0.2?

**Comment by qqplayer** [comment]
Yes I completely remove the .skyscrapper folder and then , wget , qmake....
And install again.

**Comment by muldjord** [comment]
Then it's simply because screenscraper doesn't have the exact sha1 or crc checksum of your zip files in their database. The platform bug has been fixed, which is the only thing I can think of that could be wrong.

**Comment by qqplayer** [comment]
OK Ill keep trying thanks

**Comment by muldjord** [comment]
Btw, try unzipping the roms, that might help screenscraper identify them by checksum.

I'll close the issue for now.

**Comment by qqplayer** [comment]
Hi again , I don´t want to be a pain but the thing is for me still doesn´t work.
I´ve changed my files and now as you can see the "crc" matches exactly but I get the same result.

`
3e8759e3
`

[img]https://i.imgur.com/yBmR006.png[/img]

[img]https://i.imgur.com/NxpB4Uq.png[/img]



I also make a clean install on my pi , roms on msx folder and this is my command:

`pi@retropie:~/sources/skyscraper-2.0.2 $ Skyscraper -p 'msx' -s 'screenscraper'
------------------------------------------
Running Skyscraper v2.0.2 by Lars Muldjord
------------------------------------------
Platform        : 'msx'
Scraper module  : 'screenscraper'
Input folder    : '/home/pi/RetroPie/roms/msx'
Gamelist folder : '/home/pi/RetroPie/roms/msx'
Images folder   : '/home/pi/RetroPie/roms/msx/images'
Local db folder : 'dbs/msx'

Folder '/home/pi/RetroPie/roms/msx/images' doesn't exist, trying to create it... Success!

Looking for optional 'priorities.xml' file in local db folder... Found!
Priorities loaded successfully!


Starting scraping run on 5 files using 4 threads.
Sit back, relax and let me do the work! :)

#1/5 Pass 1 Pass 2 Pass 3 ---- Game '1942 (Japan)' not found :( ----


Elapsed time: 00:00:01
Estimated time: 00:00:05

#2/5 Pass 1 Pass 2 Pass 3 ---- Game 'Alges no Yoku (Japan)' not found :( ----


Elapsed time: 00:00:01
Estimated time: 00:00:02

#3/5 Pass 1 Pass 2 Pass 3 ---- Game 'AcroJet (Japan)' not found :( ----


Elapsed time: 00:00:01
Estimated time: 00:00:02

#4/5 Pass 1 Pass 2 Pass 3 ---- Game 'Aleste (Japan)' not found :( ----


Elapsed time: 00:00:01
Estimated time: 00:00:01

#5/5 Pass 1 Pass 2 Pass 3 ---- Game 'American Soccer (Japan)' not found :( ----


Elapsed time: 00:00:01
Estimated time: 00:00:01

---- Scraping run completed! YAY! ----
Writing 0 resources to local database, please wait... Success!
Now writing '/home/pi/RetroPie/roms/msx/gamelist.xml'... Success!!!

---- And here are some neat stats :) ----
Total completion time: 00:00:01

Total number of games: 5
Successfully scraped games: 0
Skipped games: 5 (Filenames saved to 'skipped-screenscraper.txt')`

Is this the "update" file?

wget https://github.com/muldjord/skyscraper/archive/2.0.2.tar.gz

Sorry to reply again but can´t find a solution.

**Comment by muldjord** [comment]
I'll look into this when I get the time and see if I can figure out what's
wrong

**Comment by qqplayer** [comment]
I'll appreciate , thanks.

**Comment by muldjord** [comment]
I can reproduce the problem here now, I'll fix it... hang on.

**Comment by muldjord** [comment]
The issue should be fixed now. Please download the 2.0.3 release and try it out.

**Comment by qqplayer** [comment]
Hi muldjord , you are right , now is working , thanks for the fix

**Comment by muldjord** [comment]
You're welcome, enjoy!
