### ISSUE TITLE
Attractmode module needs updaing

### ISSUE THREAD

**Issue by zkvsky** [muldjord/skyscraper#176]
Overview metadata was moved into ~/.attract/scraper/**emuname**/overview/**romname**.txt [ extension changed from *.cfg]

overview tag was removed from the beginning of the info

**Comment by muldjord** [comment]
Thanks for letting me know. I'll look into it for 3.3.4.

**Comment by teeedubb** [comment]
I can confirm this.

**Comment by muldjord** [comment]
I've been looking over their release notes and I [can't find anything](https://github.com/mickelson/attract/releases) about this change. Please look through this and point me to the change so I can confirm this somehow. I don't use attract-mode myself so I need some documentation on this. And I would probably need to implement a version check so I don't break it for other users.

**Comment by muldjord** [comment]
I've been looking through their source code now, and I still can't find anything that corresponds to this change. Where are you running this where this change exists?

**Comment by zkvsky** [comment]
Standard Linux distro? ( Gentoo ) 
I've started using it recently ( 2.6 or master ) and it's the default behaviour.
I shouldn't probably say that it was changed, as I'm not sure, lemme browse through their stuff

**Comment by zkvsky** [comment]
> I've been looking through their source code now, and I still can't find anything that corresponds to this change. Where are you running this where this change exists?

@muldjord It was changed in even older version, 2.4

Citation from the dev:

> The process you linked to has changed in AM 2.4. The "story" files are now stored in a different location, have different file extensions and have a different file structure (they are no longer prefixed with the word "overview").

I can't find it in their changelogs though... Urgh...

**Comment by zkvsky** [comment]
@muldjord Found it! It's in 2.4 changelog
Issue [#391](https://github.com/mickelson/attract/issues/391) store overview information by emulator

Sorry for the confusion, next time I'll check it first and link to the commit. We live we learn

**Comment by muldjord** [comment]
Great, that makes it a lot easier for me. This seems to have been broken for a long time then.

**Comment by zkvsky** [comment]
@muldjord My reason for using Skyscraper [ besides  that it's an amazing scraper ] is that I've been testing all three front-ends, and it just makes that that much easier.
In the end I've picked Attract and imho, it's least user friendly but most performant and has the best themes

**Comment by muldjord** [comment]
I've fixed this now on the master branch. I've tested it a bit on my RetroPie and it saves the description files in the correct place with the correct names. But the default AttractMode theme (the very basic one that comes installed with it) doesn't seem to show descriptions anywhere and I have no idea where I can look them up within AttractMode (I've never used attractmode except for some basic testing, so please excuse my noobness on this). Could you guys please test it with your themes and verify that things works correctly? Just pull from master, compile it, run "sudo make install" and try scraping a platform for attractmode. Let me know how it goes or if you have questions. Thanks!

**Comment by zkvsky** [comment]
I will in a bit, get Arcadeflow theme/layout from their forum, it has descs, it's beautiful and will help me to explain another bug that I've found related to double paths used for assets in themes ( like Arcadeflow ) which use screenshoots transistioning into videos

I have account in container in my sys, for devs testing themes for AF, if it's of any use for you let me know

**Comment by teeedubb** [comment]
Hey muldjord,

I have installed master and can confirm that the overview files are placed in the correct locations, displayed correctly and no longer have 'overview' at the start of the text. Thanks!

One thing tho, the new version no longer scrapes rar files, even with the addext option. I have both the official release and master on my system and am using the same command for both. Looking through the changelog nothing related to this jumps out at me as being changed, so not sure what it could be?

**Comment by muldjord** [comment]
@teeedubb Great! Glad to hear it works. Thanks for testing, I appreciate it! And thanks for letting me know about the addext option. That was a very silly error I've inadvertently introduced while adding some other extensions the other day. It is fixed on master now. Phew... I've given you a small shoutout in the commit.

@barolo I'd actually rather you guys tested it as I don't use Attract-Mode and would rather not install too much on my Pi that I don't use. I will use the one you pointed out in case I do end up testing it, thanks!

**Comment by zkvsky** [comment]
@muldjord  Overviews work great now, skins pick them up.

I have different issue now though. Both skins that I'm using use something like this for snaps 
`artwork    snap            ~/RetroPie/roms/genesis/assets/snap;~/RetroPie/roms/genesis/assets/video
`

which results in Skyscraper pulling assets into own folders [ I can use absolute paths if I'd have to, I'm doing relative for portability that I need ] then pulling video into another nested path:` .skyscraper/~/RetroPie/roms/genesis/assets/snap;~/RetroPie/roms/genesis/assets/video/`


( as I wrote, I can provide you remote account with everything set up )

**Comment by muldjord** [comment]
> which results in Skyscraper pulling assets into own folders [ I can use absolute paths if I'd have to, I'm doing relative for portability that I need ] then pulling video into another nested path:` .skyscraper/~/RetroPie/roms/genesis/assets/snap;~/RetroPie/roms/genesis/assets/video/`

This is not caused by the relative paths bu rather that I didn't know it could be semicolon separated. I will implement a check for `;` and also look for `videos` mentioned in those. If found it will set the video folder accordingly. Stay tuned...

**Comment by muldjord** [comment]
@barolo I have now implemented semicolon support for artwork of snaps type. It will also try and set the videos folder accordingly if a path with `video` is found as one of the semicolon separated paths. It's on master, completely untested.

**Comment by zkvsky** [comment]
@muldjord Got fresh master and it's still the same?

**Comment by muldjord** [comment]
> @muldjord Got fresh master and it's still the same?

I don't understand. Is it still the same or are you asking me?

EDIT: If it's still the same and it outputs incorrectly it might _also_ be the relative paths.

**Comment by zkvsky** [comment]
@muldjord :) Sorry, it's still the same, Imma check it with absolute now.

Edit. Absolute places assets in the correct folder but the semicolon issue is still present

**Comment by muldjord** [comment]
It should place screenshots in snaps and videos in videos with the `artwork snap /home/pi/RetroPie/roms/genesis/assets/snap;/home/pi/RetroPie/roms/genesis/assets/video`. What does it do currently do for snaps? And what does it currently do for videos?

EDIT: I think I need to rethink this a bit. If a path contains spaces it will also break currently...

**Comment by zkvsky** [comment]
There seems to be an issue with relative paths anyway as using them places assets in .skyscraper folder named "~"

[ what it does current is to place them together in video  folder at path [ literally ]: `".skyscraper/~/RetroPie/roms/genesis/assets/snap;~/RetroPie/roms/genesis/assets/video/"`

**Comment by muldjord** [comment]
Ok, just leave it then I'll do some testing myself when I get home tonight. :) Thanks!

**Comment by zkvsky** [comment]
@muldjord Sure thing, no rush, I'm placing them semi manually as a workaround.
There's another thing I probably should open separate issue for [ let me know if ] Using screenscraper [ with an account ] I'm getting 0 kb assets, for 100 roms it's around 90% for wheels and 5% for snaps, never happens with videos [ seems to be size related ], tested with 3 systems.  Maybe consider checking for 0 kb stuff and purge it from the cache?

**Comment by muldjord** [comment]
It's certainly something I need to check up on. But yes, please create a separate issue. We're branching out a bit too much in here. :laughing:

**Comment by muldjord** [comment]
Bloody hell, I had a stray 's' on 'snap' (so 'snaps') which made it not work correctly with the semicolon detection. Should be fixed on master now. I will expand it further though, so it also works with paths that have spaces in them. In those cases would it use `"` to escape them? For instance, would the line be `artwork snap "~/RetroPie/roms/Sega Genesis/assets/snap";"~/RetroPie/roms/Sega Genesis/assets/video"`? @barolo

EDIT: So I think I've figured it out. It doesn't seem to require quotes around paths with spaces in them, so I'll just support both. Stay tuned...

EDIT2: Almost there, but it's currently broken so please don't test right now.

EDIT3: Implementation done and on master. Also tested it a bit and seems to work. Please test @barolo
- Supports quoted paths if it's even relevant
- Supports spaces in paths
- Supports `~` which is transformed to the user home folder

I tested it with this:
```
artwork    flyer           /home/pi/RetroPie/roms/snes/flyer
artwork    marquee         /home/pi/RetroPie/roms/snes/marquee
artwork    snap            "/home/pi/Retro Pie/roms/snes/snap";~/RetroPie/roms/snes/video
artwork    wheel           /home/pi/RetroPie/roms/snes/wheel
```
Which gives paths detected like this:
```
Covers folder:      '/home/pi/RetroPie/roms/snes/flyer'
Screenshots folder: '/home/pi/Retro Pie/roms/snes/snap'
Wheels folder:      '/home/pi/RetroPie/roms/snes/wheel'
Marquees folder:    '/home/pi/RetroPie/roms/snes/marquee'
Videos folder:      '/home/pi/RetroPie/roms/snes/video'
```

**Comment by teeedubb** [comment]
Thanks muldjord!
Also thanks for your work on this scraper - it's awesome and it takes my frontend to the next level.

**Comment by muldjord** [comment]
Thanks, I'm glad it proves useful. :)

**Comment by zkvsky** [comment]
@muldjord Works beautifully now, thanks! Think we can close this one.

**Comment by muldjord** [comment]
Awesome! Closing

**Comment by muldjord** [comment]
3.3.4 now released with these changes included.
